apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-build
  labels:
    app: content-build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-build
  template:
    metadata:
      labels:
        app: content-build
    spec:
      containers:
      - name: content-build
        image: {{ .Values.contentBuildImage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-website
  labels:
    app: ray-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-website
  template:
    metadata:
      labels:
        app: ray-website
    spec:
      containers:
      - name: ray-website
        image: {{ .Values.webAppImage }}

