name: Build and push Docker image
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-image:${{ github.sha }} .
      - name: Login to Docker Hub
        run: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - name: Push Docker image
        run: docker push "$DOCKER_PASSWORD"/argocd

